import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./styles.css";
import "./globals.css";
import SideBar from "./components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discord Clone App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "Whitney" }}>
        <div className="flex text-white h-screen">
          <SideBar />
          {children}
        </div>
      </body>
    </html>
  );
}
